---
slug: discover_game_design
filename: discover_game_design
title: Discover Game Design
subtitle: The Developer's Guide To Completing Your Game
description: Jumpstart your idea. Gain an audience. Become a professional.
author: Jeremy Alexander
copyright: 2017
uuid: 9bf9a677-abd1-45a1-84ff-f7f31f31bdab
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
